networks:
  ngi_web:

services:
  ngi_db:
    container_name: ngi_db
    # Need MariaDB because mysql doesn't play nicely with M1 Macs
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - ngi_web
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  ngi_wordpress:
    container_name: ngi_wordpress
    depends_on:
      - ngi_db
    image: wordpress:latest
    volumes:
      - ./wp-content/plugins/methods/:/var/www/html/wp-content/plugins/methods/
      - ./wp-content/themes/ngisweden/:/var/www/html/wp-content/themes/ngisweden/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./htaccess-dev:/var/www/html/.htaccess
    networks:
      - ngi_web
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: ngi_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "true"
