version: "3.9"

services:
  ngi_db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      # This line mounts a local MySQL dump into the initdb so that it is loaded on run
      - ./wp-content/database.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: ${NGI_WP_DB_NAME}
      MYSQL_USER: ${NGI_WP_DB_USER}
      MYSQL_PASSWORD: ${NGI_WP_DB_PASSWORD}

  ngi_wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${NGI_WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${NGI_WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${NGI_WP_DB_NAME}
volumes:
  db_data: {}
  wordpress_data: {}
